### PR TITLE
FIX Don't blindly assume that HOME is writable

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Follow up of #42 for SS3.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Sorry for the noise. Totally would've made more sense to do this and the patch on merge up. Oh well.

**Review by robbieaverill — APPROVED** [review]
LGTM, can you please deploy this to a CWP test instance and run the updates job to ensure it works before we merge though?

**Comment by ScopeyNZ** [comment]
Sorry about this - it's dropped off my radar. I'll try to get around to this this week.

**Comment by NightJar** [comment]
⏲ :trollface: 

Busy is as busy does.

Do you think you'll have time to remember what this is about some time soon @ScopeyNZ ?

**Comment by ScopeyNZ** [comment]
Tested and it's fine. Nothing in the logs 🚀

**Pull request merged**
