### PR TITLE
DEP PHP Support in CMS5

### PR DESCRIPTION
**Pull request by sabina-talipova**
### Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10402

### CODE REVIEW

**Review by emteknetnz — COMMENTED** [review]
Will wait until https://github.com/bringyourownideas/silverstripe-maintenance/pull/184 is resolved before approving, should rerun tests on this post merge on that one

**Comment by sabina-talipova** [comment]
https://github.com/bringyourownideas/silverstripe-maintenance/pull/184 passed tests

**Comment by emteknetnz** [comment]
I left some review comments on https://github.com/bringyourownideas/silverstripe-maintenance/pull/184

**Comment by sabina-talipova** [comment]
> bringyourownideas/silverstripe-maintenance#184

DONE

**Comment by sabina-talipova** [comment]
Passed tests in local environment

**Review by maxime-rainville — APPROVED** [review]
LGTM

**Pull request merged**
